[package]
name = "console_wrapper_r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.3"
serde_json = "1.0.114"
walkdir = "2.5.0"
